### ISSUE TITLE
Seems cool but ...

### ISSUE THREAD

**Issue by julcod** [SlicedSilver/autocomplete-polymer#13]
Hi,

I've tried to install the package but I've got a error  that I don't understand. Missing some stuff to install before ou bug ?

```
Installing “autocomplete-polymer@0.2.4” failed.Hide output…

> git-utils@3.0.1 install C:\Users\Julien\AppData\Local\Temp\apm-install-dir-11608-21420-1qw09ag\node_modules\autocomplete-polymer\node_modules\scandal\node_modules\git-utils
> node-gyp rebuild


C:\Users\Julien\AppData\Local\Temp\apm-install-dir-11608-21420-1qw09ag\node_modules\autocomplete-polymer\node_modules\scandal\node_modules\git-utils>if not defined npm_config_node_gyp (node "C:\Users\Julien\AppData\Local\atom\app-1.3.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Julien\\AppData\\Local\\atom\\app-1.3.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Julien\\AppData\\Local\\atom\\app-1.3.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Julien\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Julien\\.atom\\.apmrc" "install" "C:\\Users\\Julien\\AppData\\Local\\Temp\\d-11608-21420-ra22hu\\package.tgz" "--target=0.34.3" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! git-utils@3.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the git-utils@3.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the git-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls git-utils
npm ERR! There is likely additional logging output above.
```

**Comment by sufiyanghori** [comment]
+1

**Comment by sufiyanghori** [comment]
had a similar issue so I installed it manually instead.
CD to`~/.atom/packages`
then clone the project,
`git clone https://github.com/SlicedSilver/autocomplete-polymer`
cd to `autocomplete-polymer`
run `npm install`

Restart atom

**Comment by RenanRB** [comment]
Hi sufiyamghori, performed the procedure, however, is now taking place the following error:

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Unknown Windows Version
**Thrown From**: [autocomplete-polymer](https://github.com/SlicedSilver/autocomplete-polymer) package, v0.2.4

### Stack Trace

Failed to load the autocomplete-polymer package

```
At Cannot find module 'scandal'

Error: Cannot find module 'scandal'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (C:\Users\renan.bertoldo\AppData\Local\atom\app-1.11.2\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (C:\Users\renan.bertoldo\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\renan.bertoldo\.atom\packages\autocomplete-polymer\lib\updater.js:1:90)
    at Module._compile (C:\Users\renan.bertoldo\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\renan.bertoldo\AppData\Local\atom\app-1.11.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\renan.bertoldo\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/renan.bertoldo/.atom/packages/autocomplete-polymer/lib/main.coffee:4:11)
    at Object.<anonymous> (file:///C:/Users/renan.bertoldo/.atom/packages/autocomplete-polymer/lib/main.coffee:1:1)
    at Module._compile (C:\Users\renan.bertoldo\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\renan.bertoldo\AppData\Local\atom\app-1.11.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\renan.bertoldo\AppData\Local\atom\app-1.11.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\renan.bertoldo\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:721:27)
    at C:\Users\renan.bertoldo\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\renan.bertoldo\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\renan.bertoldo\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\renan.bertoldo\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:457:14)
    at C:\Users\renan.bertoldo\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:402:19
    at Config.module.exports.Config.transact (C:\Users\renan.bertoldo\AppData\Local\atom\app-1.11.2\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\renan.bertoldo\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:397:19)
    at C:\Users\renan.bertoldo\AppData\Local\atom\app-1.11.2\resources\app.asar\src\atom-environment.js:759:28
```
