### ISSUE TITLE
Uncaught TypeError: Cannot read property 'paper-button-icon' of undefined

### ISSUE THREAD

**Issue by chuckh** [SlicedSilver/autocomplete-polymer#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.205.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-polymer](https://github.com/SlicedSilver/autocomplete-polymer) package, v0.2.2
### Stack Trace

Uncaught TypeError: Cannot read property 'paper-button-icon' of undefined

```
At /Users/chuckh/.atom/packages/autocomplete-polymer/lib/provider.coffee:270

TypeError: Cannot read property 'paper-button-icon' of undefined
  at Object.module.exports.getTagAttributes (/Users/chuckh/.atom/packages/autocomplete-polymer/lib/provider.coffee:270:52)
  at Object.module.exports.getAttributeNameCompletions (/Users/chuckh/.atom/packages/autocomplete-polymer/lib/provider.coffee:103:22)
  at Object.module.exports.getSuggestions (/Users/chuckh/.atom/packages/autocomplete-polymer/lib/provider.coffee:22:8)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:255:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:234:17)
  at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:221:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61

```
### Commands

```
     -0:03.9.0 core:paste (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "angularjs",
      "atom-handlebars",
      "save-session",
      "polymer-snippets"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-paths, v1.0.2
autocomplete-polymer, v0.2.2
color-picker, v2.0.4
command-logger, v0.23.0
compare-files, v0.4.1
editor-stats, v0.17.0
language-actionscript, v0.2.0
linter-htmlhint, v0.0.16
pretty-json, v0.3.3
project-manager, v1.15.7

# Dev
No dev packages
```

**Comment by chuckh** [comment]
Looks like running Update Project Completions Dictionary fixed the problem.
