### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dom-module' of undefined

### ISSUE THREAD

**Issue by lukszy** [SlicedSilver/autocomplete-polymer#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.206.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-polymer](https://github.com/SlicedSilver/autocomplete-polymer) package, v0.2.2
### Stack Trace

Uncaught TypeError: Cannot read property 'dom-module' of undefined

```
At /Users/lukasz/.atom/packages/autocomplete-polymer/lib/provider.coffee:270

TypeError: Cannot read property 'dom-module' of undefined
  at Object.module.exports.getTagAttributes (/Users/lukasz/.atom/packages/autocomplete-polymer/lib/provider.coffee:270:52)
  at Object.module.exports.getAttributeNameCompletions (/Users/lukasz/.atom/packages/autocomplete-polymer/lib/provider.coffee:103:22)
  at Object.module.exports.getSuggestions (/Users/lukasz/.atom/packages/autocomplete-polymer/lib/provider.coffee:22:8)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:255:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:234:17)
  at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:221:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61

```
### Commands

```
     -0:10.7.0 core:move-down (atom-text-editor.editor.is-focused)
  5x -0:10.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:09.8.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:09.8.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:09.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:08.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:07.9.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:07.7.0 core:select-down (atom-text-editor.editor.is-focused)
  9x -0:07.4.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:06.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:05.3.0 core:move-up (atom-text-editor.editor.is-focused)
  4x -0:05.1.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:04.3.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:03.9.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -0:03.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:02.0 core:undo (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "angularjs",
      "ease-blink",
      "whitespace"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```
### Installed Packages

``` coffee
# User
angularjs-snippets, v0.10.2
autocomplete-polymer, v0.2.2
caniuse, v0.5.3
emmet, v2.3.10
git-log, v0.4.1
git-projects, v1.14.1
highlight-selected, v0.9.3
linter, v0.12.6
linter-jscs, v1.12.0
linter-jshint, v0.1.6
linter-less, v0.4.0
minimap, v4.9.3
pigments, v0.4.4
project-manager, v1.15.8
seti-syntax, v0.4.0
seti-ui, v0.7.1
tabs-to-spaces, v0.11.0
tool-bar, v0.1.5

# Dev
No dev packages
```

**Comment by SlicedSilver** [comment]
Version 0.2.3 should fix this error.
