### ISSUE TITLE
Uncaught TypeError: Cannot read property 'undefined' of undefined

### ISSUE THREAD

**Issue by techniq** [SlicedSilver/autocomplete-polymer#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-polymer](https://github.com/SlicedSilver/autocomplete-polymer) package, v0.2.2
### Stack Trace

Uncaught TypeError: Cannot read property 'undefined' of undefined

```
At /Users/smlynch/Google Drive/Backups/dotfiles/.atom/packages/autocomplete-polymer/lib/provider.coffee:179

TypeError: Cannot read property 'undefined' of undefined
  at Object.module.exports.getAttributeValues (/Users/smlynch/Google Drive/Backups/dotfiles/.atom/packages/autocomplete-polymer/lib/provider.coffee:179:41)
  at Object.module.exports.getAttributeValueCompletions (/Users/smlynch/Google Drive/Backups/dotfiles/.atom/packages/autocomplete-polymer/lib/provider.coffee:131:15)
  at Object.module.exports.getSuggestions (/Users/smlynch/Google Drive/Backups/dotfiles/.atom/packages/autocomplete-polymer/lib/provider.coffee:18:8)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:255:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:234:17)
  at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:221:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61

```
### Commands

```
     -0:18.7.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-seti-ui.find-visible)
     -0:18.6.0 blur (body.platform-darwin)
  5x -0:16.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:12.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:10.8.0 core:select-all (atom-text-editor.editor.mini.is-focused)
  2x -0:08.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:07.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.1.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:07.1.0 autocomplete-polymer:update (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-seti-ui.find-visible)
     -0:04.8.0 blur (body.platform-darwin)
     -0:04.2.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  4x -0:03.9.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:03.0 vim-mode:delete (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:02.9.0 vim-mode:till (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
  3x -0:02.9.0 blur (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
     -0:02.3.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "deprecation-cop",
      "autocomplete",
      "symbols-tree-view",
      "linter-eslint"
    ],
    "themes": [
      "seti-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-alignment, v0.12.1
atom-jinja2, v0.5.0
atom-ternjs, v0.6.4
atom-yeoman, v0.3.6
autocomplete-polymer, v0.2.2
editor-stats, vundefined
editorconfig, vundefined
gist-it, v0.7.0
highlight-selected, vundefined
language-docker, vundefined
language-ini, v1.10.0
linter, v0.12.6
linter-jshint, v0.1.6
minimap, v4.9.4
monokai, v0.14.0
omnisharp-atom, v0.12.0
project-manager, v1.15.10
seti-monokai, vundefined
seti-syntax, vundefined
seti-ui, v0.7.1
unity-ui, vundefined
vim-mode, v0.51.0

# Dev
No dev packages
```

**Comment by SlicedSilver** [comment]
Version 0.2.3 should fix this error.

**Comment by techniq** [comment]
Thanks
